# Generated by Django 6.0.2 on 2026-04-16 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lengthInSeconds', models.PositiveIntegerField()),
                ('track', models.FileField(upload_to='songs/')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dateOfCreation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateOfCreation'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='musicaaApp.song')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('motivation', 'Motivation'), ('calm', 'Calm'), ('romantic', 'Romantic')], max_length=20)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('classical', 'Classical'), ('latin', 'Latin'), ('alternative', 'Alternative'), ('indie', 'Indie')], max_length=20)),
                ('occasion', models.CharField(choices=[('wedding', 'Wedding'), ('party', 'Party'), ('birthday', 'Birthday')], max_length=20)),
                ('prompt', models.TextField()),
                ('singerIsMale', models.BooleanField()),
                ('lengthInSeconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form', to='musicaaApp.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
