# Generated by Django 6.0.2 on 2026-04-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicaaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
