# Generated by Django 6.0.2 on 2026-04-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicaaApp', '0002_song_audio_url_alter_song_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='genre',
            field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('classical', 'Classical'), ('latin', 'Latin'), ('alternative', 'Alternative'), ('indie', 'Indie')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('motivation', 'Motivation'), ('calm', 'Calm'), ('romantic', 'Romantic')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='occasion',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('party', 'Party'), ('birthday', 'Birthday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
