# Generated by Django 6.0.2 on 2026-04-25 15:17

import uuid
from django.db import migrations, models


def populate_share_tokens(apps, schema_editor):
    Song = apps.get_model('musicaaApp', 'Song')
    for song in Song.objects.all():
        song.share_token = uuid.uuid4()
        song.save(update_fields=['share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('musicaaApp', '0003_alter_form_genre_alter_form_mood_alter_form_occasion_and_more'),
    ]

    operations = [
        # Step 1: Add the field as nullable (no unique yet) so existing rows get a value
        migrations.AddField(
            model_name='song',
            name='share_token',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: Fill each existing row with a unique UUID
        migrations.RunPython(populate_share_tokens, migrations.RunPython.noop),
        # Step 3: Enforce default + unique now that all rows are populated
        migrations.AlterField(
            model_name='song',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
